// Writes tools/nn/gpusim-params.json: what the GPU training simulator (tools/nn/gpusim.py) takes
// from the real game: robot specs, field obstacles, starting spots, the FUEL layout, timing.
// Re-run it after changing the robots or the field:
//   node --import ./tools/node-env.mjs tools/nn/gpusim-export.mjs
import fs from 'node:fs';
import { createWorld } from '../headless.mjs';
import { Robot } from '../../js/robot.js';
import { Match } from '../../js/match.js';
import { ROBOTS, ROBOT_ORDER, fitsTrench } from '../../js/robotConfigs.js';
import { START_POSITIONS, START_ORDER, startPose } from '../../js/auto.js';
import { OBSTACLES, TRENCH_ARMS } from '../../js/nav.js';
import { Field } from '../../js/field.js';
import * as THREE from 'three';
import { solveMovingShot } from '../../js/ballistics.js';
import {
  HALF_L, HALF_W, HUB, FUEL, TIMING, POINTS, OUTPOST, BLUE, PHYSICS_DT, TRENCH,
} from '../../js/constants.js';
import { OBS_DIM, OBS_VERSION, OBS_LAYOUT, DECISION_DT } from '../../js/nn/obs.js';

const world = await createWorld();
const match = new Match({ playerAlliance: BLUE });
world.fuel.match = match;

const robots = {};
for (const key of ROBOT_ORDER) {
  const cfg = ROBOTS[key];
  const r = new Robot({ cfg, alliance: BLUE, physics: world.physics, scene: world.scene, field: world.field, fuel: world.fuel, match, climber: null });
  r.spawn(0, 0, 0);
  r.hopperDeploy = 0;
  const capIn = r.capacity();
  r.hopperDeploy = 1;
  const capOut = r.capacity();
  const sh = cfg.shooter, ic = cfg.intake, d = cfg.drive;
  // flywheel speed a stationary shot needs at each distance (null: out of range)
  const h0 = sh.type === 'fixed' ? sh.exit.y : sh.exitY;
  const hc = Field.hubCenter(BLUE);
  const shotV = (table, d, tx) => { const s = solveMovingShot(table, new THREE.Vector3(tx - d, h0, 0), { x: 0, z: 0 }, { x: tx, z: 0 }); return s ? +s.v.toFixed(3) : null; };
  const hubV = [], passV = [];
  for (let d = 0; d <= 12; d += 0.5) hubV.push(shotV(r.hubTable, d, hc.x));
  for (let d = 0; d <= 20; d += 0.5) passV.push(shotV(r.passTable, d, 0));
  const starts = {};
  for (const k of START_ORDER) { const p = startPose(k, r, BLUE); starts[k] = [p.x, p.z]; }
  robots[key] = {
    halfL: r.halfL, halfW: r.halfW, height: cfg.height, mass: cfg.mass,
    maxSpeed: d.maxSpeed, maxAccel: d.maxAccel, maxOmega: d.maxOmega, maxAlpha: d.maxAlpha,
    intakeWidth: ic.width, intakeReach: ic.reach, intakeRate: ic.rate, deployTime: ic.deployTime,
    latched: !!ic.latched, capIn, capOut, capMax: r.maxCapacity(),
    turret: sh.type !== 'fixed', turrets: sh.turrets ? sh.turrets.length : 1,
    bps: sh.bps, spinTau: sh.spinTau, speedMax: sh.speedMax, turretRate: sh.turretRate || 0, turretRange: sh.turretRange || 0,
    fitsTrench: fitsTrench(cfg), starts, aimOffset: r.aimOffset, hubV, passV,
  };
  r.destroy();
}

// FUEL as the real game stages it with 8 preloaded per robot (2 robots)
const pre = world.fuel.stage(16);
const field = world.fuel.balls.filter((b) => b.state === 'field').map((b) => [+b.pos.x.toFixed(4), +b.pos.z.toFixed(4)]);

const outposts = {};
for (const a of ['blue', 'red']) {
  const o = world.field.outposts[a];
  outposts[a] = { throw: [o.hpThrowPos.x, o.hpThrowPos.y, o.hpThrowPos.z] };
}

const out = {
  note: 'Generated by tools/nn/gpusim-export.mjs from the real game. Do not edit by hand.',
  obs: { version: OBS_VERSION, dim: OBS_DIM, layout: OBS_LAYOUT, decisionDt: DECISION_DT },
  field: { halfL: HALF_L, halfW: HALF_W, allianceLineX: Field.allianceLineX(BLUE), hubX: Field.hubCenter(BLUE).x },
  hub: { size: HUB.size, exitWidth: HUB.exitWidth, exitHeight: HUB.exitHeight, scoreGrace: HUB.scoreGrace },
  fuel: { radius: FUEL.radius, total: FUEL.total, rollDecel: FUEL.rollDecel, restitution: FUEL.restitution, perChute: FUEL.perChute, preload: pre.length / 2, field },
  obstacles: OBSTACLES.map((o) => ({ x: o.x, z: o.z, hx: o.hx, hz: o.hz, kind: o.kind })),
  trenchArms: TRENCH_ARMS.map((a) => ({ x: a.x, z: a.z, hx: a.hx, hz: a.hz })),
  trench: { clearHeight: TRENCH.clearHeight },
  timing: TIMING, points: POINTS, physicsDt: PHYSICS_DT,
  outposts, chuteCapacity: OUTPOST.chuteCapacity,
  startOrder: START_ORDER, startNames: Object.fromEntries(START_ORDER.map((k) => [k, START_POSITIONS[k].name])),
  robotOrder: ROBOT_ORDER, robots,
};
const file = new URL('./gpusim-params.json', import.meta.url);
fs.writeFileSync(file, JSON.stringify(out, null, 1));
console.log(`wrote ${file.pathname}: ${ROBOT_ORDER.length} robots, ${field.length} FUEL on the field, obs ${OBS_DIM}`);
world.physics.world.free();
